# Generated by Django 3.2.7 on 2021-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211114_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='devliveredAt',
            new_name='deliveredAt',
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
